### ISSUE TITLE
"/c%d" incorrectly identified as "malformed URI"

### ISSUE THREAD

**Issue by kevinbader** [odogono/elixir-jsonpointer#3]
According to the [spec](https://tools.ietf.org/html/rfc6901#section-5) `/c%d` should be a valid query string. See the following IEx session for details.

```iex
Erlang/OTP 21 [erts-10.0.7] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Interactive Elixir (1.7.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> doc = ~S"""
...(1)>    {
...(1)>       "foo": ["bar", "baz"],
...(1)>       "": 0,
...(1)>       "a/b": 1,
...(1)>       "c%d": 2,
...(1)>       "e^f": 3,
...(1)>       "g|h": 4,
...(1)>       "i\\j": 5,
...(1)>       "k\"l": 6,
...(1)>       " ": 7,
...(1)>       "m~n": 8
...(1)>    }
...(1)> """
"   {\n      \"foo\": [\"bar\", \"baz\"],\n      \"\": 0,\n      \"a/b\": 1,\n      \"c%d\": 2,\n      \"e^f\": 3,\n      \"g|h\": 4,\n      \"i\\\\j\": 5,\n      \"k\\\"l\": 6,\n      \" \": 7,\n      \"m~n\": 8\n   }\n"
iex(2)> map = Jason.decode!(doc)
%{
  "" => 0,
  " " => 7,
  "a/b" => 1,
  "c%d" => 2,
  "e^f" => 3,
  "foo" => ["bar", "baz"],
  "g|h" => 4,
  "i\\j" => 5,
  "k\"l" => 6,
  "m~n" => 8
}
iex(3)> JSONPointer.get(map, "/c%d")
** (ArgumentError) malformed URI "c%d"
    (elixir) lib/uri.ex:334: URI.decode/1
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (odgn_json_pointer) lib/json_pointer.ex:859: JSONPointer.parse/1
    (odgn_json_pointer) lib/json_pointer.ex:441: JSONPointer.walk_container/4
    (odgn_json_pointer) lib/json_pointer.ex:72: JSONPointer.get/2
```

**Comment by odogono** [comment]
Fixed in 2.4.0 - thanks!
